apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mariadb-template-instance
  namespace: default
spec:
  clusterServiceClassExternalName: mariadb-template
  clusterServicePlanExternalName: mariadb-plan1
  parameters:
    APP_NAME: mariadb-sample-app
    DB_STORAGE: "10Gi"
    SERVICE_TYPE: ClusterIP
    MYSQL_USER: root1
    MYSQL_PASSWORD: tmax@23
    MYSQL_DATABASE: root1