apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: mariadb-template
  annotations:
    template-version: 1.2.2
    tested-operator-version: 4.1.3.2
shortDescription: MariaDB Deployment
longDescription: MariaDB Deployment
urlDescription: https://mariadb.org/
imageUrl: https://upload.wikimedia.org/wikipedia/commons/c/c9/MariaDB_Logo.png
provider: tmax
tags:
- db
- mariadb
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-service
    labels:
      app: ${APP_NAME}
  spec:
    type: ${SERVICE_TYPE}
    ports:
    - port: 3306
    selector:
      app: ${APP_NAME}
      tier: mariadb
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-pvc
    labels:
      app: ${APP_NAME}
  spec:
    storageClassName: csi-cephfs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${DB_STORAGE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret
  type: Opaque
  stringData:
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}-mariadb
    labels:
      app: ${APP_NAME}
  spec:
    selector:
      matchLabels:
        app: ${APP_NAME}
        tier: mariadb
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          tier: mariadb
      spec:
        containers:
        - image: 192.168.6.110:5000/centos/mariadb:10.2
          name: mariadb
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: MYSQL_DATABASE
          ports:
          - containerPort: 3306
            name: mariadb
          volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql/data
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            exec:
              command:
              - /bin/bash
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
        volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: ${APP_NAME}-pvc
parameters:
- name: APP_NAME
  displayName: AppName
  description: Application name
  required: true
- name: DB_STORAGE
  displayName: DBStorage
  description: Storage size for DB
  required: true
- name: SERVICE_TYPE
  displayName: ServiceType
  description: Service Type (ClsuterIP/NodePort/LoadBalancer)
  required: true
- name: MYSQL_USER
  displayName: MysqlUser
  description: MysqlUser
  required: true
- name: MYSQL_PASSWORD
  displayName: MysqlPassword
  description: MysqlPassword
  required: true
- name: MYSQL_DATABASE
  displayName: MysqlDatabase
  description: MysqlDatabase
  required: true
plans:
- name: mariadb-plan1
  description: mariadb
  metadata:
    bullets:
    - 'Storage Capacity: 5Gi'
    costs:
      amount: 100
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          DB_STORAGE: 5Gi
          APP_NAME: mariadb-deploy
          MYSQL_USER: root1
          MYSQL_PASSWORD: tmax@23
          MYSQL_DATABASE: root1
- name: mariadb-plan2
  description: mariadb
  metadata:
    bullets:
    - 'Storage Capacity: 30Gi'
    costs:
      amount: 500
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          DB_STORAGE: 30Gi
          APP_NAME: mariadb-deploy
          MYSQL_USER: root1
          MYSQL_PASSWORD: tmax@23
          MYSQL_DATABASE: root1
