apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: postgresql-template
  annotations:
    template-version: 1.2.2
    tested-operator-version: 4.1.3.2
shortDescription: PostgreSQL Deployment
longDescription: PostgreSQL Deployment
urlDescription: https://www.postgresql.org/
imageUrl: https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg
provider: tmax
tags:
- db
- postgresql
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-service
    labels:
      app: ${APP_NAME}
  spec:
    type: ${SERVICE_TYPE}
    ports:
    - port: 5432
    selector:
      app: ${APP_NAME}
      tier: postgresql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-pvc
    labels:
      app: ${APP_NAME}
  spec:
    storageClassName: csi-cephfs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${DB_STORAGE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret
  type: Opaque
  stringData:
    POSTGRESQL_USER: ${POSTGRESQL_USER}
    POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
    POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}-postgresql
    labels:
      app: ${APP_NAME}
  spec:
    selector:
      matchLabels:
        app: ${APP_NAME}
        tier: postgresql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          tier: postgresql
      spec:
        containers:
        - image: 192.168.6.110:5000/centos/postgresql:9.6
          name: postgresql
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: POSTGRESQL_USER
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: POSTGRESQL_PASSWORD
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: POSTGRESQL_DATABASE
          ports:
          - containerPort: 5432
            name: postgresql
          volumeMounts:
          - name: postgresql-persistent-storage
            mountPath: /var/lib/pgsql/data
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            exec:
              command:
              - /usr/libexec/check-container
        volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: ${APP_NAME}-pvc
parameters:
- name: APP_NAME
  displayName: AppName
  description: Application name
  required: true
- name: DB_STORAGE
  displayName: DBStorage
  description: Storage size for DB
  required: true
- name: SERVICE_TYPE
  displayName: ServiceType
  description: Service Type (ClsuterIP/NodePort/LoadBalancer)
  required: true
- name: POSTGRESQL_USER
  displayName: PostgreSQLUser
  description: PostgreSQLUser
  required: true
- name: POSTGRESQL_PASSWORD
  displayName: PostgreSQLPassword
  description: PostgreSQLPassword
  required: true
- name: POSTGRESQL_DATABASE
  displayName: PostgreSQLDatabase
  description: PostgreSQLDatabase
  required: true
plans:
- name: postgresql-plan1
  description: postgresql
  metadata:
    bullets:
    - 'Storage Capacity: 5Gi'
    costs:
      amount: 100
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          DB_STORAGE: 5Gi
          APP_NAME: postgresql-deploy
          POSTGRESQL_USER: root
          POSTGRESQL_PASSWORD: tmax@23
          POSTGRESQL_DATABASE: root
- name: postgresql-plan2
  description: postgresql
  metadata:
    bullets:
    - 'Storage Capacity: 30Gi'
    costs:
      amount: 500
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          DB_STORAGE: 30Gi
          APP_NAME: postgresql-deploy
          POSTGRESQL_USER: root
          POSTGRESQL_PASSWORD: tmax@23
          POSTGRESQL_DATABASE: root
