apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: pypi-package-server-instance
  namespace: default
spec:
  clusterServiceClassExternalName: pypi-package-server
  clusterServicePlanExternalName: pypi-plan0
  parameters:
    DEPLOY_NAME: pypi-private-1
    STORAGE: 10Gi
