apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: archiva-package-server-instance
  namespace: default
  annotations:
    template-version: 1.2.2
    tested-operator-version: 4.1.3.2
spec:
  clustertemplate:
    metadata:
      name: archiva-package-server
    parameters:
    - name: DEPLOY_NAME
      value: archiva-private-1
    - name: STORAGE
      value: 10Gi

