apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: nodejs-mysql-template-instance
  namespace: default
  annotations:
    template-version: 1.2.2
    tested-operator-version: 4.1.3.2
spec:
  clustertemplate:
    metadata:
      name: nodejs-mysql-template
    parameters:
    - name: APP_NAME
      value: nodejs-mysql-sample-app
    - name: SERVICE_ACCOUNT_NAME
      value: tutorial-service
    - name: DB_SERVICE_TYPE
      value: ClusterIP
    - name: WAS_SERVICE_TYPE
      value: LoadBalancer
    - name: WAS_PORT
      value: 3000
    - name: DB_STORAGE
      value: 20Gi
    - name: MYSQL_USER
      value: root1
    - name: MYSQL_PASSWORD
      value: tmax@23
    - name: MYSQL_DATABASE
      value: root1
    - name: GIT_URL
      value: https://github.com/sunghyunkim3/nodejs-mysql-crud
    - name: GIT_REV
      value: master
    - name: IMAGE_URL
      value: 192.168.6.110:5000/nodejs-sample
    - name: REGISTRY_SECRET
      value: ''
    - name: REGISTRY_ID
      value: ''
    - name: REGISTRY_PW
      value: ''
    - name: PACKAGE_SERVER_URL
      value: ''
    - name: DEPLOY_RESOURCE_CPU
      value: 500m
    - name: DEPLOY_RESOURCE_MEM
      value: 500Mi
