apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mongodb-template-instance
  namespace: default
spec:
  clusterServiceClassExternalName: mongodb-template
  clusterServicePlanExternalName: mongodb-plan1
  parameters:
    parameters:
    APP_NAME: mongodb-sample-app
    DB_STORAGE: "10Gi"
    SERVICE_TYPE: ClusterIP
    MONGODB_USER: root
    MONGODB_PASSWORD: root
    MONGODB_DATABASE: root
    MONGODB_ADMIN_PASSWORD: root
