apiVersion: tmax.io/v1
kind: ClusterTemplate
metadata:
  name: mongodb-template
  namespace: default
  annotations:
    template-version: 1.2.2
    tested-operator-version: 4.1.3.2
shortDescription: MongoDB Deployment
longDescription: MongoDB Deployment
urlDescription: https://www.mongodb.com/
imageUrl: https://upload.wikimedia.org/wikipedia/en/4/45/MongoDB-Logo.svg
provider: tmax
tags:
- db
- mongodb
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-service
    labels:
      app: ${APP_NAME}
  spec:
    type: ${SERVICE_TYPE}
    ports:
    - port: 27017
    selector:
      app: ${APP_NAME}
      tier: mongodb
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-pvc
    labels:
      app: ${APP_NAME}
  spec:
    storageClassName: csi-cephfs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${DB_STORAGE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret
  type: Opaque
  stringData:
    MONGODB_USER: ${MONGODB_USER}
    MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    MONGODB_DATABASE: ${MONGODB_DATABASE}
    MONGODB_ADMIN_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}-mongodb
    labels:
      app: ${APP_NAME}
  spec:
    selector:
      matchLabels:
        app: ${APP_NAME}
        tier: mongodb
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          tier: mongodb
      spec:
        containers:
        - image: 192.168.6.110:5000/centos/mongodb:2.6
          name: mongodb
          env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: MONGODB_USER
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: MONGODB_PASSWORD
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: MONGODB_DATABASE
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: MONGODB_ADMIN_PASSWORD
          ports:
          - containerPort: 27017
            name: mongodb
          volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /var/lib/mongodb/data
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            exec:
              command:
              - /bin/bash
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
        volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: ${APP_NAME}-pvc
parameters:
- name: APP_NAME
  displayName: AppName
  description: Application name
  required: true
- name: DB_STORAGE
  displayName: DBStorage
  description: Storage size for DB
  required: true
- name: SERVICE_TYPE
  displayName: ServiceType
  description: Service Type (ClsuterIP/NodePort/LoadBalancer)
  required: true
- name: MONGODB_USER
  displayName: MongoDBUser
  description: MongoDBUser
  required: true
- name: MONGODB_PASSWORD
  displayName: MongoDBPassword
  description: MongoDBPassword
  required: true
- name: MONGODB_DATABASE
  displayName: MongoDBDatabase
  description: MongoDBDatabase
  required: true
- name: MONGODB_ADMIN_PASSWORD
  displayName: MongoDBAdminPassword
  description: MongoDBAdminPassword
  required: true
plans:
- name: mongodb-plan1
  description: mongodb
  metadata:
    bullets:
    - 'Storage Capacity: 5Gi'
    costs:
      amount: 100
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          DB_STORAGE: 5Gi
          APP_NAME: mongodb-deploy
          MONGODB_USER: root
          MONGODB_PASSWORD: root
          MONGODB_DATABASE: root
          MONGODB_ADMIN_PASSWORD: root
- name: mongodb-plan2
  description: mongodb
  metadata:
    bullets:
    - 'Storage Capacity: 30Gi'
    costs:
      amount: 500
      unit: $
  free: false
  bindable: true
  plan_updateable: false
  schemas:
    service_instance:
      create:
        parameters:
          DB_STORAGE: 30Gi
          APP_NAME: mongodb-deploy
          MONGODB_USER: root
          MONGODB_PASSWORD: root
          MONGODB_DATABASE: root
          MONGODB_ADMIN_PASSWORD: root
